# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clean-bitmask-attribute}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavel Chipiga", "Bruce Williams"]
  s.date = %q{2010-07-05}
  s.email = %q{pavel.chipiga@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/bitmask-attribute.rb",
     "lib/bitmask_attribute.rb",
     "lib/bitmask_attribute/attribute.rb",
     "lib/bitmask_attribute/core_ext/blank.rb",
     "lib/bitmask_attribute/core_ext/hash_with_indifferent_access.rb",
     "lib/bitmask_attribute/core_ext/returning.rb",
     "lib/bitmask_attribute/value_proxy.rb",
     "rails/init.rb",
     "test/bitmask_attribute_test.rb",
     "test/clean_bitmask_attribute_test.rb",
     "test/clean_test_helper.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/chipiga/bitmask-attribute/tree/clean}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple bitmask attribute support for any class}
  s.test_files = [
    "test/bitmask_attribute_test.rb",
     "test/clean_bitmask_attribute_test.rb",
     "test/clean_test_helper.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

